//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSDTCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;

    public partial class Flight
    {
        public int FlightId { get; set; }
        public string FilghtName { get; set; }
        public string Number { get; set; }
        public System.DateTime TravellingDate { get; set; }


        public void AddFlight(Flight flight)
        {   
            string connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["Flight"].ConnectionString;

            using (SqlConnection connection = new SqlConnection(connectionString))
            {

                using (SqlCommand cmd = new SqlCommand())
                {
                    // define parameters and their values
                    cmd.Parameters.Add("@Flightid", SqlDbType.VarChar, 50).Value = flight.FlightId;
                    cmd.Parameters.Add("@FlightName", SqlDbType.VarChar, 50).Value = flight.FilghtName;
                    cmd.Parameters.Add("@Number", SqlDbType.VarChar, 50).Value = flight.Number;
                    cmd.Parameters.Add("@TravellingDate", SqlDbType.VarChar, 50).Value = flight.TravellingDate;

                    // open connection, execute INSERT, close connection
                    cmd.CommandText = "INSERT INTO FLIGHT(Flightid, FlightName,Number,TravellingDate) VALUES(@Flightid, @FlightName,@Number,@TravellingDate)";
                    cmd.Connection = connection;
                    connection.Open();
                    cmd.ExecuteNonQuery();
                }
            }

        }

    }

}
