//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSDTCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Data;
    using System.Configuration;

    public partial class Hotel
    {
        public int BookingId { get; set; }
        public string Name { get; set; }
        public System.DateTime BookingDate { get; set; }


        public void AddHotel(Hotel hotel)
        {
            string connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["Hotel"].ConnectionString;

            using (SqlConnection connection = new SqlConnection(connectionString))
            {

                using (SqlCommand cmd = new SqlCommand())
                {
                    // define parameters and their values
                    cmd.Parameters.Add("@BookingId", System.Data.SqlDbType.VarChar, 50).Value = hotel.BookingId;
                    cmd.Parameters.Add("@Name", SqlDbType.VarChar, 50).Value = hotel.Name;
                    cmd.Parameters.Add("@BookingDate", SqlDbType.VarChar, 50).Value = hotel.BookingDate;

                    if (hotel.Name == "Bomb") throw new Exception();

                    // open connection, execute INSERT, close connection
                    cmd.CommandText = "INSERT INTO Hotel(BookingId, Name,BookingDate) VALUES(@BookingId, @Name,@BookingDate)";
                    cmd.Connection = connection;
                    connection.Open();
                    cmd.ExecuteNonQuery();
                }
            }

        }
    }
}
